name: shesha-core-3.x.x

on:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: '6.x'

jobs:

  # build the project
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout latest code
      - name: Get Sources
        uses: actions/checkout@v2
        with:
          clean: true
      # setup .net core
      - name: Use .NET Core SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      # dotnet restore
      - name: Dotnet Restore
        run: dotnet restore --configfile .nuget/NuGet.Config --verbosity detailed

      # build Shesha (Solution)
      - name: Dotnet Build
        run: dotnet build --configuration Release

      # tag branch
      - name: Tag Branch
        id: tag_version
        uses: iilyichev/github-tag-action@v6.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          tag_filter: "^3."
      # pack Shesha (Solution)
      - name: Dotnet Pack Shesha
        run: dotnet pack -o ../dist -p:PackageVersion=${{ steps.tag_version.outputs.new_tag }} -p:Version=${{ steps.tag_version.outputs.new_tag }} --include-symbols --include-source
      
      # create github release
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          
      # push nuget packages
      - name: Dotnet Nuget Push
        run: dotnet nuget push "../dist/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
