name: shesha-core-0.x.x

on:
  push:
    branches: [ main ]

jobs:

  # create a version and tag the branch
  version:
    runs-on: ubuntu-latest
    steps:
    - name: Bump Version and Push Tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ""
      

  # package:
  #   runs-on: ubuntu-latest
  #   needs: version
  #   steps:

    
  # publish:
  #   runs-on: ubuntu-latest
  #   needs: [version, package]
  #   steps:

