name: shesha-core-0.x.x

on:
  push:
    branches: [ main ]

jobs:

  version:
    runs-on: ubuntu-latest

  package:
    needs: version
    runs-on: ubuntu-latest
    
  publish:
    needs: [version, package]
    runs-on: ubuntu-latest
